#!/bin/env python

MAX_NUM=100
MIN_NUM=1

def fib(n):
    if n == 0:
        return 0
    elif n == 1:
        return 1
    else:
        return fib(n-1) + fib(n-2)

def main():
    answer = 0;
    print "Project Euler ID #2"
    print "Each new term in the Fibonacci sequence is generated by adding two terms."
    print "By starting with 1 and 2, the first 10 items will be: "
    print
    print "1, 1, 2, 3, 4, 8, 13, 21, 34, 55, 89, ..."
    print 
    print "By considering the terms in the Fibonacci sequence whose values do not"
    print "exceed four million, find the sum of the even-valued terms."
    print

    for num in range(MIN_NUM, MAX_NUM):
        if fib(num) < 4000000:
            if fib(num)%2 == 0:
                answer += fib(num)

    print "Final Answer: ", answer

main()
